name: Run Minecraft Bot 24/7

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes to keep it awake

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'  # Match your Node version from package.json
      - run: npm install  # Install dependencies
      - run: node index.js  # Run your bot’s main file (change if it’s different)